services:
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "${QBITTORRENT_WEBUI_PORT:-8080}:8080"
      - "${QBITTORRENT_INCOMING_PORT:-8999}:8999"
    volumes:
      - ${CONFIG_ROOT:-/data/config}/vpn:/gluetun
    environment:
      - VPN_TYPE=openvpn
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=${VPN_USERNAME}+nr+pmp
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_ENDPOINT_PORT=443
      - SERVER_COUNTRIES=Netherlands
      - VPN_PORT_FORWARDING=on
      - TZ=${TZ}
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- https://ipinfo.io/ip || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - media

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:vpn"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_ROOT:-/data/config}/qbittorrent:/config
      - ${DOWNLOADS_ROOT:-/data/downloads}:/downloads
    depends_on:
      vpn:
        condition: service_healthy

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${PLEX_ADVERTISE_IP}
    volumes:
      - ${CONFIG_ROOT:-/data/config}/plex:/config
      - ${MEDIA_ROOT:-/data/media}:/data/media
    devices:
      - /dev/dri:/dev/dri
    ports:
      - "32400:32400"
    networks:
      - media
      - edge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.tls.certresolver=letsencrypt"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT:-/data/config}/sonarr:/config
      - ${MEDIA_ROOT:-/data/media}/tv:/tv
      - ${DOWNLOADS_ROOT:-/data/downloads}:/downloads
    ports:
      - "8989:8989"
    networks:
      - media
      - edge
    depends_on:
      qbittorrent:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=letsencrypt"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT:-/data/config}/radarr:/config
      - ${MEDIA_ROOT:-/data/media}/movies:/movies
      - ${DOWNLOADS_ROOT:-/data/downloads}:/downloads
    ports:
      - "7878:7878"
    networks:
      - media
      - edge
    depends_on:
      qbittorrent:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls.certresolver=letsencrypt"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT:-/data/config}/prowlarr:/config
    ports:
      - "9696:9696"
    networks:
      - media
      - edge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls.certresolver=letsencrypt"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - media

networks:
  media:
    name: media
  edge:
    name: edge
