version: "3.9"

services:
  vpn:
    image: qmcgaw/gluetun:v3.38.0
    container_name: vpn
    cap_add:
      - NET_ADMIN
    ports:
      - "${QBITTORRENT_WEBUI_PORT:-8080}:8080"
      - "${QBITTORRENT_INCOMING_PORT:-8999}:8999"
    volumes:
      - ${CONFIG_ROOT:-/data/config}/vpn:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_USER=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - SERVER_COUNTRIES=${VPN_COUNTRY}
      - TZ=${TZ}
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- https://ipinfo.io/ip || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - media

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.6-ls248
    container_name: qbittorrent
    network_mode: "service:vpn"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_ROOT:-/data/config}/qbittorrent:/config
      - ${DOWNLOADS_ROOT:-/data/downloads}:/downloads
    depends_on:
      vpn:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v2/app/version"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

  plex:
    image: lscr.io/linuxserver/plex:1.40.4.8670-607c2f179-ls228
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${PLEX_ADVERTISE_IP}
    volumes:
      - ${CONFIG_ROOT:-/data/config}/plex:/config
      - ${MEDIA_ROOT:-/data/media}:/data/media
    devices:
      - /dev/dri:/dev/dri
    ports:
      - "32400:32400"
    networks:
      - media
      - edge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.tls.certresolver=letsencrypt"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.docker.network=edge"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:32400/identity"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.9.2264-ls254
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT:-/data/config}/sonarr:/config
      - ${MEDIA_ROOT:-/data/media}/tv:/tv
      - ${DOWNLOADS_ROOT:-/data/downloads}:/downloads
    networks:
      - media
      - edge
    depends_on:
      qbittorrent:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/ping"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=letsencrypt"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.sonarr.middlewares=default-security@file"
      - "traefik.docker.network=edge"

  radarr:
    image: lscr.io/linuxserver/radarr:5.10.3-ls229
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT:-/data/config}/radarr:/config
      - ${MEDIA_ROOT:-/data/media}/movies:/movies
      - ${DOWNLOADS_ROOT:-/data/downloads}:/downloads
    networks:
      - media
      - edge
    depends_on:
      qbittorrent:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878/ping"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls.certresolver=letsencrypt"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.middlewares=default-security@file"
      - "traefik.docker.network=edge"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.15.2.4364-ls106
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PROWLARR__AUTHENTICATIONMETHOD=External
      - PROWLARR__APIKEY=${PROWLARR_API_KEY}
    volumes:
      - ${CONFIG_ROOT:-/data/config}/prowlarr:/config
    networks:
      - media
      - edge
    depends_on:
      vpn:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696/ping"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls.certresolver=letsencrypt"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - "traefik.http.routers.prowlarr.middlewares=default-security@file"
      - "traefik.docker.network=edge"

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.18
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    networks:
      - media
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8191/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  media:
    name: media
    internal: true
  edge:
    name: edge
